### ISSUE TITLE
Error: Calling Formula.sha1 is disabled!

### ISSUE THREAD

**Issue by makoni** [crossroadlabs/homebrew-tap#9]
Error in HomeBrew. Log:

```
mak$ brew upgrade
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/crossroadlabs/homebrew-tap/Formula/libevhtp.rb:7:in `<class:Libevhtp>'
Please report this to the crossroadlabs/tap tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/crossroadlabs/homebrew-tap/Formula/libevhtp.rb:7:in `<class:Libevhtp>'
/usr/local/Homebrew/Library/Taps/crossroadlabs/homebrew-tap/Formula/libevhtp.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:200:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:240:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:271:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:254:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1357:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1355:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by durul** [comment]
+1
